name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    outputs:
        status: ${{ job.status }}
    defaults:
        run:
            working-directory: terraform


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=ce7-backend-bucket" -backend-config="region=us-east-1"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply --auto-approve tfplan
