name: Terraform CI  # Workflow name

on: 
  push:             # Trigger this workflow on any push event to any branch

jobs:
  terraform-ci:     # Job name
    runs-on: ubuntu-latest    # Use the latest Ubuntu runner for the job

    steps:
      ## Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3