name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -backend-config="bucket=ce7-backend-bucket" -backend-config="region=us-east-1"

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform TFLint Check
        uses: terraform-linters/setup-tflint@v1
        with:
          version: latest

      - name: Run TFLint
        working-directory: ./terraform
        run: tflint
