name: Terraform CI  # Workflow name

on:
    pull_request:
      branches:
        - main

jobs:
  terraform-ci:     # Job name
    runs-on: ubuntu-latest    # Use the latest Ubuntu runner for the job
    outputs:
        status: ${{ job.status }}
    defaults:
        run:
            working-directory: terraform # Points to Terraform folder

    steps:
        # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4
    
        ## Step 2: Configure AWS credentials for Terraform to access AWS resources
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}         # Store AWS access key as secret
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Store AWS secret key as secret
            aws-region: us-east-1                                       # Set AWS region

        # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
    
      #Step 4: Initialize Terraform
      - name: Terraform init
        run: terraform init